# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: 2022 CoG Robomaster Sim2Real Challenge
short_description: This competition is themed around EP robots, and we will provide simulation environments and real life scenarios. Robots need to continuously search for sequential QR codes in a specified map, while avoiding collisions with static obstacles and other moving robots in the environment. The robot that completes the search for the QR code in the fastest and safest way will win the competition. There are two tracks, the first one is simpler, which is investigates the basic algorithm, the second one is more difficult, which is investigates some reinforcement learning algorithms. We will provide a simulation environment which can be used by reinforcement learning algorithms and other learning algorithms. We will provide motion planning、localization、shutting、rule decision and reinforcement learning baseline algorithms. The competition will be divided into three stages. In the first stage, the competition will be carried out in the simulation environment, in the second stage, the competition will be carried out in the actual robot field, and in the third stage, the scheme defense will be carried out.
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Now, wo only use score which can be calculated by the way mationed in the Evaluation to judge which team is better.
evaluation_script: evaluation_script.zip
remote_evaluation: True
is_docker_based: False
start_date: 2022-03-15 00:00:00
end_date: 2022-08-15 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Score"],
        "default_order_by": "Score",
        "metadata": {
          "Score": {
            "sort_ascending": True,
            "description": "The only metric to meature the algorithm's level.",
          }
        }
      }
      
challenge_phases:
  - id: 1
    name: Simulation Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2022-03-15 00:00:00
    end_date: 2022-05-31 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: Simulation
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 100
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".zip"
    
  - id: 2
    name: Reality Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2022-06-06 00:00:00
    end_date: 2022-07-31 23:59:59
    test_annotation_file: annotations/test_annotations_testsplit.json
    codename: Reality
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 100
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".zip"
    
    dataset_splits:
  - id: 1
    name: Simulation Phase
    codename: Simulation
  - id: 2
    name: Reality Phase
    codename: Reality

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
